// Copyright (c) 2017, Minerhub. All rights reserved. Use of this source code
// is governed by a BSD-style license that can be found in the LICENSE file.

class CpuFlag {
  final String CodeName;
  final String Name;

  const CpuFlag(this.CodeName, this.Name);

  String toString() => this.Name;

  /// Common flag definition
  static const Map<String, String> Common = const {
    "fpu": "Floating-Point Unit",
    "vme": "Virtual 8086 Mode Enhancements",
    "de": "Debugging Extensions",
    "pse": "Page Size Extensions",
    "tsc": "Time Stamp Counter",
    "msr": "Model-Specific Registers",
    "pae": "Physical Address Extensions",
    "mce": "Machine Check Exception",
    "cx8": "CMPXCHG8",
    "apic": "Advanced Programmable Interrupt Controller",
    "x2apic": "x2 Advanced Programmable Interrupt Controller",
    "extapic": "Extended Programmable Interrupt Controller",
    "sep": "SYSENTER/SYSEXIT",
    "mtrr": "Memory Type Range Registers",
    "pge": "Page Global Enable",
    "mca": "Machine Check Architecture",
    "cmov": "Conditional Move",
    "fcmov": "Floating Point Conditional Move",
    "pat": "Page Attribute Table",
    "pse36": "36-bit Page Size Extension",
    "pn": "Processor serial number",
    "clflush": "Cache Line Flush",
    "dts": "Debug Store",
    "acpi": "Advanced Configuration and Power Interface",
    "mmx": "Multimedia Extensions",
    "fxsr": "FXSAVE/FXRSTOR",
    "sse": "Streaming SIMD Extensions",
    "sse2": "Streaming SIMD Extensions 2",
    "pni": "Streaming SIMD Extensions 3",
    "ssse3": "Supplemental Streaming SIMD Extensions 3",
    "sse4_1": "Streaming SIMD Extensions 4.1",
    "sse4_2": "Streaming SIMD Extensions 4.2",
    "sse4a": "Streaming SIMD Extensions 4a",
    "ss": "Cache Snooping",
    "ht": "Hyper-Threading",
    "tm": "Thermal Monitor",
    "tm2": "Thermal Monitor 2",
    "pbe": "Pending Break Enable",
    "syscall": "Fast System Call",
    "mp": "Multiprocessing Capable",
    "nx": "Execute Disable",
    "mmxext": "MMX Extensions",
    "fxsr_opt": "FXSAVE/FXRSTOR",
    "pdpe1gb": "1Gb Pages",
    "rdtscp": "Read Time-Stamp Counter and Processor ID",
    "lm": "Long Mode",
    "3dnowext": "3DNow! Extensions",
    "3dnow": "3DNow!",
    "3dnowprefetch": "3DNow! Prefetch",
    "recovery": "CPU Recovery Mode",
    "longrun": "LongRun power control",
    "lrti": "LongRun Table Interface",
    "pclmulqdq": "Perform a Carry-Less Multiplication of Quadword instruction",
    "dtes64": "64-bit Debug Store",
    "monitor": "Monitor/Mwait (SSE3)",
    "ds_cpl": "CPL Qual. Debug Store",
    "vmx": "Intel Virtualization VT-x",
    "smx": "Intel Trusted Execution Technology", // Correct?
    "est": "Enhanced SpeedStep",
    "cid": "Context ID",
    "sdbg": "Silicon Debug",
    "fma": "Fused Multiply–Add",
    "fma3": "Fused Multiply–Add 3",
    "fma4": "Fused Multiply–Add 4",
    "cx16": "CMPXCHG16B",
    "xtpr": "Send Task Priority Messages",
    "pdcm": "Performance Capabilities",
    "pcid": "Process Context Identifiers",
    "dca": "Direct Cache Access",
    "movbe": "Move Data After Swapping Bytes",
    "popcnt": "POPCNT Instruction",
    "tsc_deadline_timer": "Tsc Deadline Timer",
    "aes": "Advanced Encryption Standard",
    "aes-ni": "Advanced Encryption Standard, New Instructions",
    "xsave": "Save Processor Extended States",
    "avx": "Advanced Vector Extensions",
    "avx2": "Advanced Vector Extensions 2",
    "avx512f": "Advanced Vector Extensions 512 Foundation",
    "avx512dq": "Advanced Vector Extensions 512 Double/Quad",
    "avx512pf": "Advanced Vector Extensions 512 Prefetch",
    "avx512er": "Advanced Vector Extensions 512 Exponential & Reciprocal",
    "avx512cd": "Advanced Vector Extensions 512 Conflict Detection",
    "avx512bw": "Advanced Vector Extensions 512 Byte/Word",
    "avx512vl": "Advanced Vector Extensions 512 128/256 Vector Length",
    "f16c": "CV16T",
    "rdrand": "Read Random Number",
    "hypervisor": "Over Hypervisor",
    "rng": "Random Number Generator",
    "ace": "Advanced Cryptography Engine",
    "ace2": "Advanced Cryptography Engine 2",
    "phe": "PadLock Hash Engine",
    "pmm": "PadLock Montgomery Multiplier",
    "lahf_lm": "Load AH from Flags in Long Mode",
    "svm": "AMD Virtualization AMD-V",
    "abm": "Advanced Bit Manipulation",
    "osvw": "OS Visible Workaround",
    "ibs": "Instruction Based Sampling",
    "xop": "Extended AVX",
    "skinit": "SKINIT/STGI",
    "wdt": "Watchdog Timer",
    "lwp": "Light Weight Profiling",
    "tce": "Translation Cache Extension",
    "nodeid_msr": "NodeId MSR",
    "tbm": "Trailing Bit Manipulation",
    "topoext": "Topology Extensions",
    "perfctr_core": "Core Performance Counter Extensions",
    "perfctr_nb": "NB Performance Counter Extensions",
    "bpext": "Breakpoint Extension",
    "ptsc": "Performance Timestamp Counter",
    "perfctr_l2": "L2 Performance Counter Extensions",
    "mwaitx": "MONITORX/MWAITX",
    "fsgsbase": "FS/GS BASE",
    "tsc_adjust": "TSC Adjustment",
    "bmi1": "Bit Manipulation Extensions (1st Group)",
    "bmi2": "Bit Manipulation Extensions (2nd Group)",
    "smep": "Supervisor Mode Execution Protection",
    "hle": "Hardware Lock Elision",
    "erms": "Enhanced REP MOVSB/STOSB",
    "invpcid": "Invalidate Processor Context ID",
    "rtm": "Restricted Transactional Memory",
    "cqm": "Cache QoS Monitoring",
    "mpx": "Memory Protection Extension",
    "rdseed": "RDSEED",
    "adx": "ADCX/ADOX",
    "smap": "Supervisor Mode Access Prevention",
    "clflushopt": "CLFLUSHOPT",
    "clwb": "CLWB",
    "sha_ni": "SHA1/SHA256 Extensions",
    "cqm_llc": "LLC QoS",
    "clzero": "CLZERO",
    "irperf": "Instructions Retired Performance Counter",
    "npt": "Nested Page Table",
    "lbrv": "LBR Virtualization",
    "svm_lock": "SVM locking",
    "nrip_save": "SVM next/rip Save",
    "tsc_scale": "TSC Scaling",
    "vmcb_clean": "VMCB Clean Bits",
    "flushbyasid": "Flush-by-ASID",
    "decodeassists": "Decode Assists",
    "pausefilter": "Pause Filter",
    "pfthreshold": "Pause Filter Threshold",
    "avic": "Virtual Interrupt Controller",
    "pku": "Protection Keys for Userspace",
    "ospke": "OS Protection Keys Enable",
    "overflow_recov": "MCA Overflow Recovery",
    "succor": "Uncorrectable Error Containment and Recovery",
    "smca": "Scalable MCA",
    "swp": "SWP",
    "half": "Half-word Loads & Stores",
    "thumb": "Thumb Instruction Set",
    "thumb2": "Thumb Instruction Set 2",
    "26bit": "26 Bit Memory Address",
    "fastmult": "64 Bit Multiplication",
    "fpa": "Floating Point Accelerator",
    "vfp": "Vector Floating Point",
    "vfpvd32": "Vector Floating Point, 32 D-Registers",
    "vfpv3": "Vector Floating Point 3",
    "vfpv3d16": "Vector Floating Point 3, 16 D-Registers",
    "vfpv4": "Vector Floating Point 4",
    "edsp": "DSP Extensions",
    "java": "Jazelle Direct Bytecode eXecution",
    "iwmmxt": "Intel Wireless MMX Technology",
    "crunch": "MaverickCrunch Coprocessor",
    "thumbee": "Thumb Execution Environment",
    "neon": "Advanced SIMD 32 Bit",
    "asimd": "Advanced SIMD 64 Bit",
    "tls": "Thread-Local Storage",
    "idiva": "SDIV/UDIV, ARM Mode",
    "idivt": "SDIV/UDIV, Thumb Mode",
    "pmull": "64 to 128 Bit Multiplication",
    "pmull2": "64 to 128 Bit Multiplication"
  };
}